phips28/gh-action-bump-version

index.js
This update fixes an issue with finding the package.json file using the user-defined PACKAGEJSON_DIR (when package.json isn't in the root directory). The issue was that the actions-tookit's getPackageJSON() method only looks in the GITHUB_WORKSPACE directory, so since we weren't setting that, it was unable to find the file.
=> Fix issue with finding package.json outside of root

index.js
If this field is set to the proper user with the GITHUB_TOKEN then you can track the commits and see the user's name and profile link on the commits.
=> feat: allow email and user to be overridden

index.js
Added fallback condition to increment patch version in cases where no commits are present in the event (e.g. Pull Requests and custom events)
=> Update patch version

index.js
This PR adds support for the `!` syntax for marking a `BREAKING CHANGE`, as per the latest spec:
See points 1. and 13. from [the specification](https://www.conventionalcommits.org/en/v1.0.0/#specification)
=> feat: Add support for  syntax for breaking change.

index.js
This PR replaces `match` with `test`. `match` returns an array of the matched sections of a string, but `test` returns `true` or `false`, which is what the `includes` is checking against
=> fix: `!` breaking change syntax regex

README.md, index.js
With this PR is possible to support the pre-release:
for example `1.6.0-alpha.1`
If a commit comment contains one of the words: `pre-alpha`. `pre-beta` or `pre-rc`, the action will increase the pre-release version.
This is a fallback of major and minor.
Examples:
- "This is a **pre-alpha** version" ---> transform a version `1.6.0` into `1.6.1-alpha.0`
- "This is a **pre-alpha** version" ---> transform a version `1.6.1-alpha.0` into `1.6.1-alpha.1`
- "This is a **pre-beta** version" ---> transform a version `1.6.1-alpha.1` into `1.6.1-beta.0`
- "This is a **pre-rc** version" ---> transform a version `1.6.1-beta.0` into `1.6.1-rc.0`
- "This is an empty comment" ---> transform a version `1.6.1-rc.0` into `1.6.2`
and so on.
=> Support for prerelease and --preId

Dockerfile
Looks like you were always using the latest node slim image. NodeJS 15 just came out, and the latest slim image now uses node 15.
=> fix: use slim 14.14 image

README.md, index.js
Allows you to change the default version bump from `path` to whatever you'd like using the new `default` variable
=> Support for changing the default version bump

index.js
Hi, I'm using the last version of this github action and it doesn't resolve to patch anymore, it says
```
Couldn't find any commits in this event, incrementing patch version...
messages: []
✔  success   No version keywords found, skipping bump.
```
I believe this is because patchWords is an empty array, which then makes it enter the condition line 54, and since it's written negatively version will be set to null.
I don't really understand why patchWords is an empty array, but I'm guessing `process.env['INPUT_PATCH-WORDING']` results in an empty string. (if that wasn't the case it would crash line 31 saying `cannot read property split of undefined`).
=> Fix: Action was not default to patch anymore

index.js
#64 identified the issue, but the problem persists. From what I can tell, the value of `process.env['INPUT_PATCH-WORDING']` is the empty string, which returns `['']` when `.split(',')` is called.
so then in the conditional, `patchWords === ['']`, which evaluates to true and causes the version to be nulled out.
=> FIX: patch version bumps

README.md, action.yml, index.js
Hello, I'd like to be able to run this action on tag, but I'm getting an error of 
```
✖  fatal     Error: Command failed: git checkout 0.0.0 
error: pathspec '0.0.0' did not match any file(s) known to git.
```
I figured the easiest way is to add the ability to specify which (other) branch the version increment should be performed on.
=> Allow the version upgrade to be executed on a separate branch

README.md, action.yml, index.js
fixes #27 
Thanks for providing this action! Started using this recently and found the need for some additional functionality that an issue had been created for. Also, it appears gh has addressed it's limitations as well:
https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
=> Custom commit message option

index.js
Hey, Looks like the commit detection for previous messages doesn't work,
Causing a loop.
I think that this fixes it.
=> Fix isVersionBump detection

index.js, package.json
In my case, I wanted to cover the scenarios for all semver options - MAJOR, MINOR, PATCH, PRERELEASE.
I am using the below action config in my project:
The reason why I am defining `rc-wording: ''` is because even tho I am setting the `default: prerelease` and none of the `minor-wording, major-wording, patch-wording` matches, there is a default message for rc-wording
If the above are not included in the commit message, version bump is skipped.
I also added some comments for future contributors.
=> Fixes to include all options - MAJOR, MINOR, PATCH, PRE-RELEASE

action.yml, index.js
Hey @phips28 
This is a draft PR and I didn't even test it, but can you help me with testing it?
re #81 
The aim of this PR is to support updating `package-lock.json` together with the `package.json`
`lockfileVesion: 2` adds the info about the version in `package-lock.json` - to check it out please try to run `npm i` with npm@7 in this repo, you'll get something like this 
Package version in package.json and package-lock.json is different.
The goal of this PR is to update version in package-lock.json together with the version in package.json.
Basically you can run npm script that doesn't compare node_modules with package-lock.json and updates package-lock.json with the new version from package.json
=> Allow updating npm lockfile v2 with the new version

action.yml, index.js
Reverts phips28/gh-action-bump-version#132
This will not work with the latest version with node12. (v9)
=> Revert "Allow updating npm lockfile v2 with the new version"

README.md, action.yml, index.js, package-lock.json, tests/end-to-end/config.yaml, tests/end-to-end/index.test.js
Fixes #138.
Added a `skip-commit: boolean` option, that prevent doing a `git commit` after the version is bumped.
Also, do not hesitate to suggest better wording, on the documentation of this new option.
I've tried to add tests, but unfortunately I wasn't able to run them locally (all are failing, even from the latest version, without modifying anything). I might miss something, and help is wanted for that :nerd_face:.
Other than that, this new option is working well (tested on a project I'm working on).
=> Added option to skip commit after a bump

README.md, action.yml, index.js
- Implements a new input flag `skip-push`, default false. If true, skips pushing any commit or tag created during the version bump.
- Deprecates the input flag `push`, which was documented as skipping the push, but whose actual behavior is to skip all operations (version bump in package.json, git commit, git tag, git push). In a future major version, this flag could be renamed to `no-op`, or even just removed since its behavior can be achieved using the `if: ` conditionals in Github Actions anyway.
Tested using the end-to-end test suite (needed some modifications before it would run), over here: https://github.com/rosshamish/gh-action-bump-version/pull/1/checks
=> Implement flag "skip-push", deprecate flag "push"

README.md, action.yml, index.js
New `bump-policy` option allows for configuring whether the version bump is skipped when a previous bump is found in the commit messages. If set to `'all'` (default/original behavior), then any commit that matches the commit message regex will trigger a bump skip. When set to `'last-commit'`, only the latest commit message will be checked for a previous bump. The last possible value, `'ignore'` will bump the version whenever the action runs, regardless of the contents of commit messages.
Addresses #82
=> Feature: bump-policy option

README.md, action.yml, index.js
Added a new option to manually override the option type if the workflow was trigerred without a commit... e.g worklofw_dispatch
issue mentioned in #140
=> Add option to manually override the version type

index.js
When getPackageJson fails the build doesn't exit with error code. Seems to be because it is run within the async function (returning a promise rejection instead of an error?) 
```
(node:1496) UnhandledPromiseRejectionWarning: Error: package.json could not be found in your project's root.
at getPackageJson (/home/runner/work/_actions/phips28/gh-action-bump-version/master/index.js:240:41)
at /home/runner/work/_actions/phips28/gh-action-bump-version/master/index.js:[16](https://github.com/mindlercare/video-stream-2/runs/8224139485?check_suite_focus=true#step:2:17):15
at Object.<anonymous> (/home/runner/work/_actions/phips28/gh-action-bump-version/master/index.js:236:3)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js …
```
=> exit build with error if `getPackageJson` fails

index.js
This was added in PR #176 but never worked for `prerelease` version type
=> Fix broken version-type rc

index.js
This follows the guidelines described in
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Issue 190: Use GITHUB_OUTPUT environment file to set output.

index.js
The action allows for an input PACKAGEJSON_DIR, but the index was just looking for the environment. Setting the environment worked, but doesn't handle for the input. Another method could be having both, but this change accounts for not changing any fields
=> change environment name to INPUT_PACKAGEJSON_DIR

README.md, action.yml, index.js
New `check-last-commit-only` option allows for configuring whether the version bump should only check the last commit's message. If set to 'false' (default/original behaviour), then the check will be made on all commit messages as usual. When set to 'true', only the latest commit message will be checked for a possible bump.
Addresses https://github.com/phips28/gh-action-bump-version/issues/82 when there are no active bumpers in other branches, but one would still want to check only the last commit message. This is particularly useful when we want to check only for a merged PR title for the bumping.
=> Feature: check-last-commit-only option

index.js
When setting `major-wording` or `minor-wording` to `''` (which I assumed would disable all word search checks) it actually makes every commit a major bump, becuase it searches for that empty string in the commit message. 
This PR filters out empty strings so that the major/minor words array is empty instead, as a user would expect.
=> Filter out empty strings for major/minor bump checks

index.js
GHA fails with:
```
✖  fatal     error: pathspec 'main' did not match any file(s) known to git
git exited with code 1
✖  fatal     Failed to bump version
```
if we don't fetch the branches.
=> Tag events: Always fetch branches

index.js
Reverts phips28/gh-action-bump-version#224
fails for some users: https://github.com/phips28/gh-action-bump-version/commit/dfc3f132b5ff746744717b731acf6a1c77229a54#commitcomment-128999422
=> Revert "Tag events: Always fetch branches"

README.md, action.yml, index.js
Hello there!
Unfortunately, the provider "github.com" has been hardcoded, which makes it impossible to use this action on self-hosted instances. My PR offers the possibility to define own Git instances via an environment variable with the default fallback "github.com", which was already defined before.
=> feat: add support for alternative git provider

.gitignore, action.yml, index.js, package-lock.json, package.json
I wanted to possibility to bump preminor and premajor versions on my CI based on gitflow and semver.
So I've done this little change to make that possible.
A full working example of this change can be seen on [this example repo](https://github.com/nahuelhds/ci-semver-gitflow-actions) which is using my fork.
If anything else is required for make this PR to be merged, just let me know.
=> Upgrade to node20 + Support for choosing prepatch, preminor and premajor version types 

action.yml, index.js
In response to https://github.com/phips28/gh-action-bump-version/issues/243, I've added an option of: `git-no-verify` that will run the git commit command with the `--no-verify` option enabled.
fix #243
=> Add no-verify option for git commits

index.js
Added the --silent flag to the npm version script, to avoid unwanted output that breaks the parsing
issue: https://github.com/phips28/gh-action-bump-version/issues/249
=> feat: Added silent flag to npm version script, to avoid unwanted npm output
