phips28/gh-action-bump-version

.github/workflows/push.yml, Dockerfile, action.yml, index.js, package-lock.json, package.json
Hi, now is code from separated branch and immutable from other changes. Sorry for previous confusing changes.
=> Add tag prefix

.github/workflows/push.yml, README.md, index.js, package-lock.json, package.json
Support for "actions/checkout@v2"
=> Checkout v2

README.md, action.yml, index.js
This feature needs to work with [actions/create-release](https://github.com/actions/create-release) (that add a tag on the repo as well)
=> feat: skip repo tag step

README.md, action.yml, index.js
=> feat: customizable major and minor wording to bump new versions

index.js
=> Support running in pull requests

README.md, action.yml, index.js
=> Customizable RC and Patch wording to new bump versions

index.js
=> version bump is not pushed when tag should not pushed

action.yml, index.js
Updated the `actions.yml` file to reflect the new options and changed the environment variable used to be in the expected format
=> fix: default version bump

.github/workflows/push.yml, action.yml, index.js
I have now tested this and I also updated the doc, feel free to improve my terrible english 👍
=> Added output of the tag to the action

index.js
supported preid option for `default: prerelease`
=> supported preid for default prerelease version

README.md, action.yml, index.js
I need to generate a new version but not push until later, so I made it optional
=> Make push optional

action.yml
=> node 12 -> node 16

index.js
- fix version-type
- fix prerelease selection logic
follow up to #189
=> fix prerelease version selection when version-type is set

index.js
my PR #191 was broken because I put something in the wrong parenthesis block.
@jamestalton can you please make sure this fix will not break your workflow
- test
- test
- what
- fixed it. move outside of parens
=> version-type prerelease fix was flaky

README.md
Closes #180
I was not sure if this fit better in the attention section or at the bottom of the README. I can update it to be at the bottom if you prefer.
Thanks again for creating the action @phips28! 😄
=> Adds note to README for use with private repos

README.md, action.yml, index.js, tests/end-to-end/config.yaml
=> feat: add tagSuffix input

index.js
For more context: [#214 ](https://github.com/phips28/gh-action-bump-version/issues/214)
=> Optionally select the second element from array

index.js
https://github.com/phips28/gh-action-bump-version/issues/219
=> fallback to set-output on >> $GITHUB_OUTPUT failure

index.js
- Feature / Bugfix
Currently this action takes the output from running `npm version...` to directly parse the new version number. This PR updates the way this output is parsed to get the version number from the last line of output so that any `preversion`/`version`/`postversion` hooks can be run without their output affecting the parsed version number.
```bash
$ npm version patch
> postversion
> echo 'just running another script of sorts here...'
just running another script of sorts here...
v10.1.2
```
=> feature: npm version output parsing to allow version hooks

index.js
=> Turn off npm fund

action.yml, index.js
Added support to Deploy Keys / SSH.
Issue #260 #156
=> feat: Add support to Deploy Keys / SSH 

action.yml
Reverts phips28/gh-action-bump-version#263
=> Revert "Feat: Update to Node 22"
